"""
modules/waf.py
WAF Detection — Deteksi WAF sebelum mulai fuzzing
Mengenali signature dari WAF populer berdasarkan response header dan body
"""

import re


class WAFDetector:

    # Signature WAF: {nama: [(header_key, pattern), ...]}
    WAF_SIGNATURES = {
        'Cloudflare': [
            ('server',            r'cloudflare'),
            ('cf-ray',            r'.+'),
            ('body',              r'cloudflare|Attention Required|cf-error-details'),
        ],
        'ModSecurity': [
            ('server',            r'mod_security|ModSecurity'),
            ('body',              r'mod_security|ModSecurity|NOYB'),
            ('x-mod-security',    r'.+'),
        ],
        'Akamai': [
            ('server',            r'AkamaiGHost'),
            ('body',              r'Access Denied.*Akamai|Reference.*akamai'),
            ('x-check-cacheable', r'.+'),
        ],
        'AWS WAF': [
            ('x-amzn-requestid', r'.+'),
            ('x-amzn-trace-id',  r'.+'),
            ('body',             r'AWS WAF|Request blocked'),
        ],
        'Sucuri': [
            ('server',           r'Sucuri'),
            ('x-sucuri-id',      r'.+'),
            ('body',             r'Sucuri Website Firewall|Access Denied - Sucuri'),
        ],
        'Imperva / Incapsula': [
            ('x-iinfo',          r'.+'),
            ('x-cdn',            r'Imperva|Incapsula'),
            ('body',             r'Incapsula incident|Request unsuccessful.*Incapsula'),
        ],
        'F5 BIG-IP ASM': [
            ('x-cnection',       r'.+'),
            ('body',             r'The requested URL was rejected|F5 Networks'),
            ('server',           r'BigIP|BIG-IP'),
        ],
        'Fortinet FortiWeb': [
            ('body',             r'FortiWeb|Application Firewall'),
            ('server',           r'FortiWeb'),
        ],
        'Barracuda WAF': [
            ('server',           r'barracuda'),
            ('body',             r'barracuda|Barracuda Networks'),
        ],
        'Wordfence': [
            ('body',             r'generated by Wordfence|This response was generated by Wordfence'),
        ],
    }

    def __init__(self, requester):
        self.req = requester

    def detect(self) -> str:
        """
        Kirim request normal dan request probing untuk deteksi WAF.
        Return nama WAF atau None.
        """
        # Request 1: normal
        r1 = self.req.send({})
        if r1 is None:
            return None

        # Request 2: probe dengan payload mencurigakan
        probe_params = {'test': "' OR 1=1--", 'x': '<script>alert(1)</script>'}
        r2 = self.req.send(probe_params)
        if r2 is None:
            return None

        # Cek kedua response
        for response in [r1, r2]:
            waf = self._check_response(response)
            if waf:
                return waf

        # Cek perubahan status code — WAF sering return 403/406/429/503
        if r2['status'] in (403, 406, 429, 503) and r1['status'] not in (403, 406, 429, 503):
            return 'Unknown WAF (status-based detection)'

        return None

    def _check_response(self, response: dict) -> str:
        if not response:
            return None

        headers = {k.lower(): v.lower() for k, v in response.get('headers', {}).items()}
        body    = response.get('body', '').lower()

        for waf_name, signatures in self.WAF_SIGNATURES.items():
            matched = 0
            needed  = max(1, len(signatures) // 2)   # cukup setengah signature match
            for key, pattern in signatures:
                if key == 'body':
                    if re.search(pattern, body, re.I):
                        matched += 1
                else:
                    val = headers.get(key.lower(), '')
                    if val and re.search(pattern, val, re.I):
                        matched += 1
            if matched >= needed:
                return waf_name

        return None
